artifacts_root: /deletable/apps/CoTProject/code/mlops/artifacts


data_ingestion:
  root_dir: /deletable/apps/CoTProject/code/mlops/artifacts/data_ingestion
  source_URL: https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing
  local_data_file: /deletable/apps/CoTProject/code/mlops/artifacts/data_ingestion/data.zip
  unzip_dir: /deletable/apps/CoTProject/code/mlops/artifacts/data_ingestion


prepare_base_model:
  root_dir: /deletable/apps/CoTProject/code/mlops/artifacts/prepare_base_model
  base_model_path: /deletable/apps/CoTProject/code/mlops/artifacts/prepare_base_model/base_model.h5
  updated_base_model_path: /deletable/apps/CoTProject/code/mlops/artifacts/prepare_base_model/base_model_updated.h5




training:
  root_dir: /deletable/apps/CoTProject/code/mlops/artifacts/training
  trained_model_path: /deletable/apps/CoTProject/code/mlops/artifacts/training/model.h5