name: Basic CI Pipeline

on:
  push:
    branches: [ Hous ]
  pull_request:
    branches: [ Hous ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8' # Modify this to match your Python version

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    # Add additional steps here for running tests or other commands
